### ISSUE TITLE
Data binding with library 

### ISSUE THREAD

**Issue by patelakshay13890** [jingle1267/DataDindingSample#1]
Hey developers,  How can I use data  binding  in  my application because  I am  new to  data  binding  concept ?
I have  an  application  module  and  one  android  lib. Module  which  has  all the  entites  those  are used in app module l..
So how  can I  use  data binding  in  my  app  with  lib. Module..﻿
Which also include  dynamic inflation of view  based on parameter in some of the  entities in library module ﻿

**Comment by jingle1267** [comment]
Entites' location is not important. You can also use data-binding.  The following URL may help you. [Android Developer Data Binding](http://developer.android.com/intl/zh-cn/tools/data-binding/guide.html)
